[[server]]
name = "omv-loki"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "alerter"
deploy = true
[stack.config]
server = "omv-loki"
git_provider = "github.com"
git_account = "vikaspogu"
repo = "vikaspogu/komodo-stack"
run_directory = "alerter"
send_alerts = true
auto_update = true
pre_deploy.command = """
export SOPS_AGE_KEY_FILE=/home/vikaspogu/.sops/key.txt && /usr/local/bin/sops -d ./secrets.sops.env > secrets.env
"""

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "omv-loki"

##

[[resource_sync]]
name = "komodo-stack"
[resource_sync.config]
git_provider = "github.com"
repo = "vikaspogu/komodo-stack"
git_account = "vikaspogu"
resource_path = ["komodo.toml"]
managed = true
delete = true

[[alerter]]
name = "gotify"
[alerter.config]
enabled = true
endpoint.type = "Custom"
endpoint.params.url = "http://komodo-gotify:7000"
