services:
  filebrowser:
    image: ghcr.io/gtsteffaniak/filebrowser:0.7.5-beta
    container_name: filebrowser
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.synlo.duckdns.org`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "homepage.group=traefik"
      - "homepage.name=filebrowser"
      - "homepage.href=https://files.synlo.duckdns.org"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/filebrowser-quantum.png"
    volumes:
      - /srv/dev-disk-by-uuid-9d2e4cb9-8825-4168-8153-e020ee524474/storage0:/srv
      - database:/home/filebrowser/database
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - FILEBROWSER_ADMIN_PASSWORD=${FILEBROWSER_ADMIN_PASSWORD}
    ports:
      - 8095:8095
    networks:
      - traefik_traefik
volumes:
  database:

networks:
  traefik_traefik:
    external: true
