server:
  port: 8095
  sources:
    - path: "/srv"
auth:
  methods:
    password:
      enabled: false # set to false if you only want to allow OIDC
    oidc:
      enabled: true
      clientId: "${FILEBROWSER_OIDC_CLIENTID}"
      clientSecret: "${FILEBROWSER_OIDC_CLIENTSECRET}"
      issuerUrl: "https://auth.vikaspogu.com/authorize"
      scopes: "email openid profile"