---
volumes:
  uptimekuma-data:
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.tls=true"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptime.synlo.duckdns.org`)"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
    ports:
      - 3001:3001
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped
    networks:
      - traefik_traefik
networks:
  traefik_traefik:
    external: true