---
volumes:
  uptimekuma-data:
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.uptimekuma-http.rule=Host(`synlo.duckdns.org`)
        - traefik.http.routers.uptimekuma-http.entrypoints=http
        - traefik.http.routers.uptimekuma-http.middlewares=https-redirect
        - traefik.http.routers.uptimekuma-https.rule=Host(`synlo.duckdns.org`)
        - traefik.http.routers.uptimekuma-https.entrypoints=https
        - traefik.http.routers.uptimekuma-https.tls=true
        - traefik.http.routers.uptimekuma-https.tls.certresolver=le
        - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
    ports:
      - 3001:3001
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped
    networks:
      - traefik
networks:
  traefik:
    external: true