version: '3.6'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.synlo.duckdns.org`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "homepage.group=traefik"
      - "homepage.name=homepage"
      - "homepage.hrefl=https://homepage.synlo.duckdns.org"
    volumes:
      - homepage_data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.synlo.duckdns.org
    networks:
      - traefik_traefik
volumes:
  homepage_data:
  
networks:
  traefik_traefik:
    external: true