networks:
  komodo_default:
    external: true
services:
  sops:
    image: ghcr.io/getsops/sops:v3.10.2-alpine
    command: ["/bin/sh", "-c", "sops -d -i /secrets.sops.yaml"]
    environment:
      - SOPS_AGE_KEY_FILE=/age/key.txt
    volumes:
      - ./secrets.sops.yaml:/secrets.sops.yaml
      - /home/vikaspogu/.sops:/age:ro
  komodo-gotify:
    image: foxxmd/komodo-gotify-alerter:0.0.8
    container_name: komodo-gotify-alerter
    depends_on:
      - sops
    environment:
      - GOTIFY_OK_PRIORITY=3
      - GOTIFY_WARNING_PRIORITY=5
      - GOTIFY_CRITICAL_PRIORITY=8
      - UNRESOLVED_TIMEOUT_TYPES=ServerCpu,ServerMem,ContainerStateChange
      - UNRESOLVED_TIMEOUT=20000
    env_file: ./secrets.sops.yaml
    ports:
      - "7000:7000"
    networks:
      - komodo_default
