services:
  dozzle:
    image: amir20/dozzle:v8.12
    container_name: dozzle
    deploy:
      mode: global
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.synlo.duckdns.org`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=8070"
    environment:
      - DOZZLE_MODE=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8070:8070
    networks:
      - traefik_traefik

networks:
  traefik_traefik:
    external: true