services:
  dozzle:
    image: amir20/dozzle:v8.12
    container_name: dozzle
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.synlo.duckdns.org`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "flame.type=application"
      - "flame.name=dozzle"
      - "flame.url=https://dozzle.synlo.duckdns.org"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8081
    networks:
      - traefik_traefik
networks:
  traefik_traefik:
    external: true