services:
  beszel:
    image: henrygd/beszel:0.11
    container_name: beszel
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.synlo.duckdns.org`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "homepage.group=traefik"
      - "homepage.name=beszel"
      - "homepage.href=https://beszel.synlo.duckdns.org"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/beszel.png"
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - traefik_traefik

  beszel-agent:
    image: henrygd/beszel-agent:0.11
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE/xb5WIbmAf3cYpdBK5rW9QNDxtORqURzSvsRigzhtQ'

networks:
  traefik_traefik:
    external: true