services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.rule=Host(`beszel.synlo.duckdns.org`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - traefik_traefik

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    deploy:
      mode: global
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'

networks:
  traefik_traefik:
    external: true