{
    "data": "ENC[AES256_GCM,data:2+1vdYodyZYCv4+E+1LufKorC5f3R7ApHwCNWwzVJDplh6FlKQ4jFtgBsjFqFz11us22UJuXujlSTQnRoEQb3eoU1fUFUbgCj9dclGSuzOqfau4G+RFc3SgJAzhgFx/Qd3HgdTr0nEsLR/YrMHiwLaYd1jM1o/dMf6F/+ICBncdxYiqYnTQr0Hn8m35VGIbgUO63TJlmMuVZcJJGLO5WyjeMz91QZQYsHNnPJHd9CHDtU1vL0P1F5d/+EZLI4iUZ8kJhchm3nUdQsPOPLw5y/90f1sJwgqPef165B78vdsG9eAO5IuxjnMk9rGB4ETWmn6v1Bd/5pJl+2KIHvm+jLFwEPqtINMBl73Uiofa6/sFyvR4Xf1BL/MZn6g9sy8khSKAlPzMRSBrXyPZZWEpBQ11lwUziPkAAxEPSrOvMOg9tk+B/WlStc/i/02Uox71WJ0hirIzlyV2NmmBhTm6I/mLKnULJWCKmL8QS+cgr7rf1mmbNFnYq60ca0RRSWKAMkYQIiLH/pJG1Qcyfu0dGzsDJAIP5SJvk2y4kVcAWT/uvNSLLArAF6Kcl+u4wbUJaWpVnvkEBr+mUUmT61oCmSsxe78B4V+ZlF4+9HM/5dhW9JKTU0/PgU8koNGVmLZ8hc/qI7zMDZWi8jp99d5DE2e6uh+tNOAyzMuIt7bqJgwhXMUGD1DC4FqEve1DElQsoJYVJjTjes5M6T6AmtQilLx9idO42hYX6npgEQiUTpmX/dSYKLI7C3RmcgDnFxAwoip0UTmPzgzLzKSX5b8cPwwSLfseZY8ftkLqwJFQOIjIbXOShOmGBwMxYzFXtawiZBLE0GdwkTQ==,iv:t0FAQaHTDGvNFsOH5efFUNpD1K2dzMDc2lxmRQxXcDU=,tag:cmAtLwtPSgTX0nggSuQkJw==,type:str]",
    "sops": {
        "age": [
            {
                "recipient": "age1ulfhs490lug3kres5qm5kfdmpqmcrwsfsc03eln0s3xffndnrcwq5u86tt",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxanppWGQ4eDFoU3BYa1lR\neURLSmhWbFRidFQyR096Rm92S2ZVdkR6UFEwCjhyYmw1ZkwvLzBaQlVmck50M2tV\nVTViaGpqRldva1Y4WnI4VEl1bGMxclUKLS0tIFRZeWtEYlFka1VET0hrbXh6TU0w\nVWpQT1NFZE5TbkxaY1RwMExjRGxaV0kKarKppEcLoH6iSyEar7BJKX3e+mny3LPC\nLG2tyAtDhdZWXAi+sxjmqJyN8vZ5X07DeRCQ+ynd3WhhTk8ok3Hf9Q==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2025-06-05T14:35:12Z",
        "mac": "ENC[AES256_GCM,data:Z0F4ETsZ4C53dTvKfScnyFrOH+gIqqR7vrUt1mZxqmQ671w5yXvMslpyCAepSiOymd7e7IMTR4Mt2dXMj7ylZR82VN+stshGZSPYE7dkR0TTu75alTXCZkbmCvvqulQfCMdg+LlwuJ2hyV+e4AEwHBwP3GWLkeDVoVtbe/oBpSc=,iv:rXshCXZ6t04hrJvRdsBvZ1F1+Yu3QUb7KhGhHv5UtUE=,tag:FD0Hs/4UvyuWxdXTfdk9ag==,type:str]",
        "unencrypted_suffix": "_unencrypted",
        "mac_only_encrypted": true,
        "version": "3.10.2"
    }
}
