{
    "data": "ENC[AES256_GCM,data:QyiubuUcCDsm/IgABFtRAw2LBNR0kFzlOi3fY3sdQDUH8aBM+bdhUAxxz6i4wm3Dn4mgZSGyYoIuYKXddGdFtBi/hON++ZBGw2YBRM8f9zoMYNTHQkjP//hhcsvjq5w25fUA5nWHEh8WY1ifL3oATkPsbT6BP0E4PEInnyEKBgY/iHE3TbQD5FFJyG+c1IZ5srTKo6RfwJLLXn+NsQFSx6Yv5r9uWy6F/Ge/xRjQuazLxMwFAh0Z8W8DuWQd3YV11g3rx0v43vmoeRTr+dmUOTnyzKDDupBDmKSQ3DYknRaTRy6s+2Y9/R4j6u57I+WfDNtizPSIp20lO/c0kcyy2TWj9f6Eo6w/QKFW9CF3S+9r5Jz7Z7CzZ0rSizFx1n17xUYhX3M7UBae0Tg5Xm5naPlPbTDb3A47b2jApWix9EBRO0wdq11Y1FgCXsKUJp7rfWvSaoxb42xynvt3kfiwk/OfaYOwxtWN+1a0W7CFkpyY2ASXOBJSQdkvD/jOp7GMAtnJChcKBOx395vNTIL8pC32Gc3sGHQUdk6ld+sk8Yl0mAOxvON6+FI/xIIjyyeZJHwYcec9kJQW0xlUkyhu/WuHC6PO+1wAvrlEL9TSJeQrMrTv//kkY7NFToZ0L2pnXNolBww/xhoLpPpf9FJaonIjeYthk4xN04WwXA5gr6QAEAl158GsGoK+dvIV7+mSskIdUGwsgJOeg2d7mNuaNPv2vg3XBEf8gpcezPtuHViQQzj16E6LTbC8wRODY/RTJ4Fpbs8HRXHGHPfjpbl1eyzLJ+BDzx64ryQXYZPmlwiBLGoTSo2eBxso9In1IS+ioZNygc4sFA==,iv:m19w1Vz3jbSd4/oG6DEQM85X5tJl19UL04w60e5aFqc=,tag:NWd5pUch3u4h1D6Zyza3rw==,type:str]",
    "sops": {
        "age": [
            {
                "recipient": "age1ulfhs490lug3kres5qm5kfdmpqmcrwsfsc03eln0s3xffndnrcwq5u86tt",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMkRMbllDQWg4aW4yL3Ay\nakt2bWdKbTVyMDErUGVyYjAyZXc1RmNTbEhnCkcyZTZqdi9qdnptNm5JVVRmUGl5\nNGJ6cEpLMGFEVmhKcTRobUlpbFZIckkKLS0tIDlvYmpCQzNWbDRWYk45RlkvYXo1\nblY2eXBRV3JIcWpXVHRubWpzUnRoVDgKmnvS+pjKGVAq4jBKazK5evK3vI1AaZ8q\n4dj/sRr8MgfPcX7MnZditGsyLAaFz2yKTbU6zqNte9tiZPnjbV+8fQ==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2025-05-31T16:40:06Z",
        "mac": "ENC[AES256_GCM,data:58qqTpjQOsvDeagSYTZnPVPCQvxAxF2oejlgpE4GnIEAF74w1Qzhqz09fc0yvGxBxPh/1VbA/oQHTg1SwlgPTObo1+qd/rZ2bIuFmUHuUERSkbvYJWU1ea4CrcHwcNDXmo/2jaLirtcN0XWjCvsdm9FWcN4eHFjF8o1Y7rAHN0w=,iv:E1MKIpyXON0tT8vTZYBdryreELsTFGdKnMb4KSyVaMw=,tag:3mKzdRlNCt4mQ7OwMpzpkw==,type:str]",
        "unencrypted_suffix": "_unencrypted",
        "mac_only_encrypted": true,
        "version": "3.10.2"
    }
}
