{
    "data": "ENC[AES256_GCM,data:W4AP7XTP7AoOi+8UQx1wi1xf/XZLMrzAjWxrW3VlPjxcKDkVPTEeZtgsXeCTj5cO+TcBi7vDHRzqo42Ch0bBs6P8Go8qBQxAN9OIG//V+6PdD9YX6fHSblDKqhURT1IE5uBJ3xYYYAUH58SGs/U+0iLgUCHzWwkhO619IwUWwpnNHl5fCxhYhfioSdnXaF5EssFEI1NQv4mCr2cGx54FOuMcJO6RIKY2yoGJ8rJZtIvRRjQbSViVkprg/WfV/rG+LHg/gh+yactqDEHDlNAN1KV8pERsEq84gefc5zKQD2Dr85AupKCT4Q/CaAfRmk81GzSDSP1qzo69IOdUbWLp3puYkTDPIHco7FX87kNx99mzaeYvZzaA5+Fjly6GYi6ZC4oUxGwCHCilrUswnOPMjcvEATarQIdHjJP4guFa0GYjYWuzw/W9RGaoAO6ypS6kpHBJccVVZpZlb+6mTeaMOQkgjvdwHm2jTFveDVLbYTUjts0eWNv/6332FRf16t/jupL3+CN0UmeFYKxw6/YrYZUMPiq50L9UqyDrUrHh0YMwrblGSfZjAKzE/F74Ly+NoAaZvrvuspMGlwQF2vKMKc7RZ15f6RnMd0Go3YojKXyxS8eQukJfGRH1Pq0yBmIP3MFnqyT5cP8+Py24egTD2MYXuOJSIX8t/5nTVU8XweeyFpTGs+qDbir2FnOZmHom0eATeHQporCMZ7l6YGcF7qM4CDC7CDYqiKruu5As41T4EGsFn3SMcZ2xTS6Hn58UwymggW5jaKNE0nhliSa3/kqAG2V41Jj5CKp7nkLPh8GXtAuIfl1ZNor2JXnjI7p3yN62eZN8XTyey7o+,iv:D98nmD10+gGifbTg0ZtQ30F9R7HzQdCqNPmq3GZuDms=,tag:B7GvtnKBLjik7T37jLCpPQ==,type:str]",
    "sops": {
        "age": [
            {
                "recipient": "age1ulfhs490lug3kres5qm5kfdmpqmcrwsfsc03eln0s3xffndnrcwq5u86tt",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeGZLSHc1aFlqS3BDWWhp\nMnF1cFkxU0NTZmtGOEpsNW5zRnlrdzdZY0dnCkRlWTVoVGpzb0sxeVZPWVo0L0Z6\naVQ4UzNtV0dpQ25HNGtpbDFzUlowcXMKLS0tIDRPdm9hOEM1djlWNUJRMDBqN3Vi\ndFNmMUtxQkFGQW1maDhTR043TmZ0MkUKAWrHDwzrVMldFxRevB2m02BDuS+b7XsR\nAfvRpf/vxpG47iryyMRGgl+V9WqBN8VjGGP4OFHOpCu1M2cdKy4eFA==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2025-06-05T14:30:46Z",
        "mac": "ENC[AES256_GCM,data:Fq3RbtLv7Ckufyasq8Eh2l5K6Bo1ke0njZ6YyZPm/kRJk314lxqXZJesulMOnvFX03ilXcrvEA0DI6Gb2W32MhKP35W1hCDqzJ+zo0i96bUNhVtcz2afvoZSFvannvQVCb9VkH7vh9YiVwZgwgUKTrmb4UK9N9Ckk0H708Rufrs=,iv:bsQ8LXVxYa3j2XG5Pg7wkBRUCg3YQyzV19yvkvuXc54=,tag:9lG+uRyZGQw+IwG7ha4wtQ==,type:str]",
        "unencrypted_suffix": "_unencrypted",
        "mac_only_encrypted": true,
        "version": "3.10.2"
    }
}
