{
    "data": "ENC[AES256_GCM,data:3HN5IfeVIvyF+L3ZFwPQFczsn5JAHkrRACrF6RxV+4RtB9lU5f/sinNcg1zZl5ARSJogqVWj81PY8I4vGT/wU0mzk+F+0gFjZh4IfuLHUucG2kyFKU4W1E89QmPOrARpBm9Rwh7FcnlGpEEqKmPGvuPBZXr9ZSOMeD28fKm2XWZVmc9go72aYGce5Zn/ZdZ4lB3kHtBaiEP0r63LaX1DW9wKhJNeLFCaiw2f8RVsm49K4XAvTAJfu7frvGBd8klWVpx6+EyG2td0OSaodnQZg4MIu31P+I0tQjO7Q5ZN9Op0JwpOuUbiZLlOwApVe+obCEoVmRgdXmmK+4kfFdy5G5hE1VyYlJ5ymK96BShQXoYJ8nczckWMDJPpqIZcx63bi4D22kWTulYqXSHVGDnWqn86Jv0PhZaSC1XfAUvwUrZisg6gydwygf+S7+4khZPFXFEXfEpLU8DTOCYj0hUEM/S6NE4t7FGiPH7h5gOaRw1ZraPf63NNnuxglRBGWsyCEs138uPjZydvV9F+TrO06nCSdP1hf6vrY8B1o5U9v6Zb9KoROv9HsQWIyroP4j4J4dpJKJ18g3vDN/ot2uDw7hku0bCKqdmxWtV+x+a/eL7JU+u12WeCewfBX/nakreDRyyOfgqlZQm+mwwsvjgAo+haY9n9VJoHWptLDvuKBZGwYSVvB5MnqgOnrkmojLMt6SmO2zHt39tMCtNqB6dSsskIbK2+mveHf0thB5RTqnEVEiVVQh2q00ALWIVlmLfjtgsaomf4Qwfe,iv:0M6QNrIlSwcSoGIr+lYJCz0fxBDRvzfy6KQOfQpKLjQ=,tag:rhQt1XLX45fVQYPYKI5T7Q==,type:str]",
    "sops": {
        "age": [
            {
                "recipient": "age1ulfhs490lug3kres5qm5kfdmpqmcrwsfsc03eln0s3xffndnrcwq5u86tt",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RDY2RThqZit1ci9uSWwy\nWG9hdW5ZTzZWWjNYMVdkOFRqeFBFNlFTWUhJCjM2Q2FWa2c3STF6dThPTnVVOE0v\neitQNDRuaUFBOTJtWldUMWJXNkcvS0UKLS0tIE56aW9RVXFDbkRQRU1EQ2Q5dHdS\ndW5tM3VCaC9MMlc3MWRNakhZREJVSUUK++NdUqiuj1KEL3a7orECocrEEXBF5orJ\ncwJwwCNFl4iljopp/eOQAkIXKoJ5P2L2Gir7+tr8BIwVsRPKgczsWw==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2025-05-31T16:37:25Z",
        "mac": "ENC[AES256_GCM,data:0xXPZ1DDUesfTFybkzVT0zYBOcrFteQIqEzPXS3U8m2Vytf8SCQ03IZaDB9xeP84nRMpyIxwlZy+NzEW3uM2CAf4xQhgAwqNMsUgtsipWy+P9rEMix2s9dKc6BSVubBKOIN9FN0k/lKDOPaF78pIUDGliv8az+2sn+K0uhSKhq4=,iv:S8cdvlaQ9iwEMynb16MEzEuHDI4ml/ckr8ltZZml7kk=,tag:iYUJ8johH2EkQ28BR/lYtg==,type:str]",
        "unencrypted_suffix": "_unencrypted",
        "mac_only_encrypted": true,
        "version": "3.10.2"
    }
}
